In [12]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.feature_extraction.text import CountVectorizer

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC 

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn import metrics
import itertools

import matplotlib.pyplot as plt

import tensorflow
from tensorflow import keras

# For Natural Language Processing
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/dineshbhatotia/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#!pip install tensorflow

In [13]:
df = pd.read_csv('output.csv', encoding = "ISO-8859-1")


In [14]:
df.head(5)


author                                              title  \
0  Ashutosh R Shyam  After a lacklustre 2023, will 2024 be a year o...   
1           Michail  iQOO 12 launched in India, starting at INR 52,999   
2     ETMarkets.com  F&O stocks to buy or sell today: ICICI Bank, M...   
3         Tech Desk  iPhone 15 at Rs 35K? Check out these lucrative...   
4               PTI  Stock markets climb for 2nd day on buying in I...   

                                         description  \
0  Mega stocks such as HDFC Bank, Reliance Indust...   
1  The iQOO 12 is now official in India serving a...   
2  The S&P BSE Sensex rose nearly 400 points whil...   
3  iPhone 15 is among the most sought after smart...   
4  Among the Sensex firms, Wipro jumped over 6 pe...   

                                                 url  \
0  https://economictimes.indiatimes.com/markets/s...   
1  https://www.gsmarena.com/iqoo_12_launched_in_i...   
2  https://economictimes.indiatimes.com/markets/o...   
3  https://indianexpress.com/article/technology/i...   
4  https://indianexpress.com/article/business/mar...   

                                          urlToImage        date  \
0  https://img.etimg.com/thumb/msid-106428582,wid...  2023-12-31   
1  https://fdn.gsmarena.com/imgroot/news/23/12/iq...  2023-12-12   
2  https://img.etimg.com/thumb/msid-106199210,wid...  2023-12-22   
3  https://images.indianexpress.com/2023/12/iPhon...  2023-12-29   
4  https://images.indianexpress.com/2023/12/BSE-1...  2023-12-22   

                                             content           source.id  \
0  SynopsisMega stocks such as HDFC Bank, Relianc...  the-times-of-india   
1  The iQOO 12 is now official in India serving a...                 NaN   
2  The Indian market is likely to trade higher on...  the-times-of-india   
3  The year is almost ending. Other than thumping...                 NaN   
4  Stock markets extended gains for a second day ...                 NaN   

          source.name    symbol  result  
0  The Times of India  HDFCBANK     NaN  
1        GSMArena.com  HDFCBANK     1.0  
2  The Times of India  HDFCBANK     1.0  
3  The Indian Express  HDFCBANK     0.0  
4  The Indian Express  HDFCBANK     1.0

In [15]:
df.isna().sum()

author          49
title            0
description      0
url              0
urlToImage       8
date             0
content          0
source.id      680
source.name      0
symbol           0
result         122
dtype: int64

In [16]:
df.dropna(subset=['result'], inplace=True)

In [17]:
len(df)

1969

In [55]:
# creating train test with symbols equally represented in both group

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['symbol'])

In [56]:
train_df.head()

author                                              title  \
1171      ETMarkets.com  Stock market update: Sugar stocks up as market...   
1698    Mithun Dasgupta  Berger Paints India expects to keep growing it...   
782     The Hills Times  TotalEnergies invests USD 300 million in joint...   
381   Moneycontrol News  Tata Power gains after green energy arm bags N...   
1276                NaN  Airtel Africa promotes former Bharti Airtel ex...   

                                            description  \
1171  The 30-share BSE Sensex closed  down  170.12 p...   
1698  Aditya Birla Group's Grasim Industries enterin...   
782   Strap: TotalEnergies, holds about 19.75 per ce...   
381   TPSSL’s Solar Cell and Module Manufacturi...   
1276  (marketscreener.com) Airtel Africa PLC on Tues...   

                                                    url  \
1171  https://economictimes.indiatimes.com/markets/s...   
1698  https://www.thehindubusinessline.com/companies...   
782   https://thehillstimes.in/business/totalenergie...   
381   https://www.moneycontrol.com/news/business/sto...   
1276  https://www.marketscreener.com/quote/stock/BHA...   

                                             urlToImage        date  \
1171  https://img.etimg.com/thumb/msid-82697732,widt...  2023-12-29   
1698  https://bl-i.thgim.com/public/todays-paper/tp-...  2024-01-02   
782   https://thehillstimes.in/wp-content/uploads/20...  2023-12-27   
381   https://images.moneycontrol.com/static-mcnews/...  2023-12-18   
1276  https://www.marketscreener.com/images/twitter_...  2024-01-02   

                                                content           source.id  \
1171  NEW DELHI: Sugar shares closed lower in the Fr...  the-times-of-india   
1698  Berger Paints expects to continue growing its ...                 NaN   
782   Strap: TotalEnergies, holds about 19.75 per ce...                 NaN   
381   The Tata Power Company shares were up nearly ...                 NaN   
1276  (Alliance News) - Airtel Africa PLC on Tuesday...                 NaN   

             source.name      symbol  result  
1171  The Times of India   EICHERMOT     0.0  
1698        BusinessLine      GRASIM     1.0  
782     Thehillstimes.in  ADANIGREEN     1.0  
381         Moneycontrol  TATAMTRDVR     1.0  
1276  Marketscreener.com  BHARTIARTL     0.0

In [57]:
column_names = ['title','description', 'content' ]
data = train_df[column_names]

In [58]:
len(data)

1575

In [60]:
data.head()

title  \
1171  Stock market update: Sugar stocks up as market...   
1698  Berger Paints India expects to keep growing it...   
782   TotalEnergies invests USD 300 million in joint...   
381   Tata Power gains after green energy arm bags N...   
1276  Airtel Africa promotes former Bharti Airtel ex...   

                                            description  \
1171  The 30-share BSE Sensex closed  down  170.12 p...   
1698  Aditya Birla Group's Grasim Industries enterin...   
782   Strap: TotalEnergies, holds about 19.75 per ce...   
381   TPSSL’s Solar Cell and Module Manufacturi...   
1276  (marketscreener.com) Airtel Africa PLC on Tues...   

                                                content  
1171  NEW DELHI: Sugar shares closed lower in the Fr...  
1698  Berger Paints expects to continue growing its ...  
782   Strap: TotalEnergies, holds about 19.75 per ce...  
381   The Tata Power Company shares were up nearly ...  
1276  (Alliance News) - Airtel Africa PLC on Tuesday...

In [61]:
# Remove stop words
data.replace("[^a-zA-Z]", " ", regex=True, inplace=True) 


/var/folders/3q/2dymrhy53c75l8wxnt3h655w0000gn/T/ipykernel_83415/3110462212.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.replace("[^a-zA-Z]", " ", regex=True, inplace=True)


In [62]:
len(data)

1575

In [63]:
# lower case all text 
for name in column_names:
    data[name]=data[name].str.lower()

/var/folders/3q/2dymrhy53c75l8wxnt3h655w0000gn/T/ipykernel_83415/565915055.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[name]=data[name].str.lower()


In [64]:
data.head()

title  \
1171  stock market update  sugar stocks up as market...   
1698  berger paints india expects to keep growing it...   
782   totalenergies invests usd     million in joint...   
381   tata power gains after green energy arm bags n...   
1276  airtel africa promotes former bharti airtel ex...   

                                            description  \
1171  the    share bse sensex closed  down         p...   
1698  aditya birla group s grasim industries enterin...   
782   strap  totalenergies  holds about       per ce...   
381   tpssl      s solar cell and module manufacturi...   
1276   marketscreener com  airtel africa plc on tues...   

                                                content  
1171  new delhi  sugar shares closed lower in the fr...  
1698  berger paints expects to continue growing its ...  
782   strap  totalenergies  holds about       per ce...  
381   the  tata power company shares were up nearly ...  
1276   alliance news    airtel africa plc on tuesday...

In [65]:
merged_text = data.apply(lambda row: ' '.join(map(str, row[:])), axis=1).tolist()

In [66]:
len(merged_text)

1575

In [67]:
# Word Embedding - Using Count-Vectorizer

countvector= CountVectorizer(ngram_range=(2,2))
train_dataset_cv= countvector.fit_transform(merged_text) 

In [68]:
train_dataset_cv.shape

(1575, 16506)

In [69]:
len(train_df)

1575

In [70]:
# Random Forest

rf=RandomForestClassifier(n_estimators=200,criterion='entropy')
rf.fit(train_dataset_cv,train_df['result'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [73]:
# Multinomial Naive Bayes

nb=MultinomialNB()
nb.fit(train_dataset_cv,train_df['result'])

MultinomialNB()

In [74]:
# Logestic Regression

lr=LogisticRegression()
lr.fit(train_dataset_cv,train_df['result'])

/Users/dineshbhatotia/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [75]:
# K-Nearest Neighbor

knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
knn.fit(train_dataset_cv,train_df['result'])

KNeighborsClassifier()

In [76]:
# Support vector classifier

svm = SVC(kernel='linear', random_state=0)  
svm.fit(train_dataset_cv,train_df['result'])

SVC(kernel='linear', random_state=0)

In [82]:
# Perdorming same transformation on test data 

column_names = ['title','description', 'content' ]
test_data = test_df[column_names]

# Remove stop words
test_data.replace("[^a-zA-Z]", " ", regex=True, inplace=True)

# lower case all text 
for name in column_names:
    test_data[name]=test_data[name].str.lower()

# Merging all data
merged_text = test_data.apply(lambda row: ' '.join(map(str, row[:])), axis=1).tolist()

test_headlines = merged_text

test_dataset_cv = countvector.transform(merged_text)

/var/folders/3q/2dymrhy53c75l8wxnt3h655w0000gn/T/ipykernel_83415/1811636174.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.replace("[^a-zA-Z]", " ", regex=True, inplace=True)
/var/folders/3q/2dymrhy53c75l8wxnt3h655w0000gn/T/ipykernel_83415/1811636174.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[name]=test_data[name].str.lower()


In [86]:
# Prediciton RandomForest Classifier
predictions_rf_cv = rf.predict(test_dataset_cv)
     

# Prediciton Multinomial Naive Bayes
predictions_nb_cv = nb.predict(test_dataset_cv)
     

# Prediciton Logestic Regression
predictions_lr_cv = lr.predict(test_dataset_cv)
     

# Prediciton K-Nearest Neighbor
predictions_knn_cv = knn.predict(test_dataset_cv)
     

# Prediciton Support vector classifier
predictions_svm_cv = svm.predict(test_dataset_cv)

In [89]:
# Sample prediction

predictions_nb_cv

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 0.

In [88]:
len(predictions_svm_cv)

394

In [92]:
# CV-RF
matrix_rf_cv=confusion_matrix(test_df['result'],predictions_rf_cv)
print(matrix_rf_cv)
score_rf_cv=accuracy_score(test_df['result'],predictions_rf_cv)
print(score_rf_cv)
report_rf_cv=classification_report(test_df['result'],predictions_rf_cv)
print(report_rf_cv)

[[ 89  86]
 [ 81 138]]
0.5761421319796954
              precision    recall  f1-score   support

         0.0       0.52      0.51      0.52       175
         1.0       0.62      0.63      0.62       219

    accuracy                           0.58       394
   macro avg       0.57      0.57      0.57       394
weighted avg       0.57      0.58      0.58       394



In [93]:
# CV-NB
matrix_nb_cv=confusion_matrix(test_df['result'],predictions_nb_cv)
print(matrix_nb_cv)
score_nb_cv=accuracy_score(test_df['result'],predictions_nb_cv)
print(score_nb_cv)
report_nb_cv=classification_report(test_df['result'],predictions_nb_cv)
print(report_nb_cv)

[[109  66]
 [106 113]]
0.5634517766497462
              precision    recall  f1-score   support

         0.0       0.51      0.62      0.56       175
         1.0       0.63      0.52      0.57       219

    accuracy                           0.56       394
   macro avg       0.57      0.57      0.56       394
weighted avg       0.58      0.56      0.56       394



In [94]:
# CV-LR
matrix_lr_cv=confusion_matrix(test_df['result'],predictions_lr_cv)
print(matrix_lr_cv)
score_lr_cv=accuracy_score(test_df['result'],predictions_lr_cv)
print(score_lr_cv)
report_lr_cv=classification_report(test_df['result'],predictions_lr_cv)
print(report_lr_cv)

[[ 92  83]
 [ 82 137]]
0.5812182741116751
              precision    recall  f1-score   support

         0.0       0.53      0.53      0.53       175
         1.0       0.62      0.63      0.62       219

    accuracy                           0.58       394
   macro avg       0.58      0.58      0.58       394
weighted avg       0.58      0.58      0.58       394



In [95]:
# CV-KNN
matrix_knn_cv=confusion_matrix(test_df['result'],predictions_knn_cv)
print(matrix_knn_cv)
score_knn_cv=accuracy_score(test_df['result'],predictions_knn_cv)
print(score_knn_cv)
report_knn_cv=classification_report(test_df['result'],predictions_knn_cv)
print(report_knn_cv)

[[109  66]
 [125  94]]
0.5152284263959391
              precision    recall  f1-score   support

         0.0       0.47      0.62      0.53       175
         1.0       0.59      0.43      0.50       219

    accuracy                           0.52       394
   macro avg       0.53      0.53      0.51       394
weighted avg       0.53      0.52      0.51       394



In [96]:
# CV-SVM
matrix_svm_cv=confusion_matrix(test_df['result'],predictions_svm_cv)
print(matrix_svm_cv)
score_svm_cv=accuracy_score(test_df['result'],predictions_svm_cv)
print(score_svm_cv)
report_svm_cv=classification_report(test_df['result'],predictions_svm_cv)
print(report_svm_cv)

[[ 93  82]
 [ 80 139]]
0.5888324873096447
              precision    recall  f1-score   support

         0.0       0.54      0.53      0.53       175
         1.0       0.63      0.63      0.63       219

    accuracy                           0.59       394
   macro avg       0.58      0.58      0.58       394
weighted avg       0.59      0.59      0.59       394

